<?php declare(strict_types=1);

?>
<script type="text/x-magento-init">
	{
        "*":{
            "Magento_Ui/js/core/app": {
                "components":{
                    "startSimple":{
                    "component":"Bansi_JqueryUi/js/plain-view-model"
                	}
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimple'">
	<div>sds</div>
	<h2 data-bind="text: title"></h2>
	<div>test</div>
</div>