<?php declare(strict_types=1);

?>
<script type="text/x-magento-init">
	{
        "*":{
            "Magento_Ui/js/core/app": {
                "components":{
                    "startSimple":{
                    "component":"Bansi_JqueryUi/js/plain-view-model",
                    "base_url":"<?= $block->escapeJs($block->getBaseUrl()) ?>"
                	}
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimple'">
	
	<!-- <h2 data-bind="text: title"></h2>
	<pre data-bind="text: JSON.stringify(config,null,2)"></pre> -->
	<!-- <pre data-bind="text: output"></pre> -->
	<h3 data-bind="text: label"></h3>
	<table data-bind="foreach: items">
		<tr>
			<td data-bind="text: name"></td>
			<td data-bind="text: qty"></td>
			<td data-bind="text: price"></td>
			<td data-bind="text: $parent.rowTotal($data)"></td>
		</tr>
	</table>
	<div>Addtional Charge:<span data-bind="text: additional_charge"></span></div>
	<strong>Total: <span data-bind="text: total()"></span></strong>
</div>