<?php declare(strict_types=1);

?>
<script type="text/x-magento-init">
	{
        "*":{
            "Magento_Ui/js/core/app": {
                "components":{
                    "component-a":{
                    "component":"Bansi_JqueryUi/js/ui-component-a",
                     "provider":"component-b",
                     "providerProperty":"value"
                     
                },
                "component-b":{
                    "component":"Bansi_JqueryUi/js/ui-component-b"
                     
                     
                }
            }
        }
    }
}
</script>
<div data-bind="scope: 'component-a'">
	
<h3 data-bind="text: label"></h3>
<div data-bind="text: amount"></div>
</div>

<div data-bind="scope: 'component-b'">
    
<h3 data-bind="text: title"></h3>
<div data-bind="text: value"></div>
</div>